server:
  port: 8879
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application: 
    name: 'shopping-content-ms'
  datasource:
    username: root
    password: root
    url: 'jdbc:mysql://localhost:3306/shopdb?useUnicode=true&characterEncoding=UTF-8'
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
pagehelper:
  helper-dialect: mysql
  reasonable: true
# MinIO对象存储相关配置
minio:
  endpoint:  http://127.0.0.1:9000 #MinIO服务所在地址
  bucketName: mall #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
mybatis:
  mapper-locations: com.online.shopping.mapper/*.xml
  type-aliases-package: com.online.shopping.mapper
