server:
  port: 8081
spring:
  data:
    solr:
      host: http://127.0.0.1:8080/solr
  datasource:
    username: root
    password: root
    url: 'jdbc:mysql://localhost:3306/shopdb?useUnicode=true&characterEncoding=UTF-8'
    type: com.alibaba.druid.pool.DruidDataSource